#!/bin/sh
if test $(id -u) -ne 0; then
    echo "You need root privileges to start this programm." >&2
    exit 1
fi

rm -rf /opt/pyBristol \
       /usr/bin/pyBristol \
       /usr/share/applications/pyBristol.desktop \
       /usr/share/pixmaps/pyBristol.svg

if test $? -eq 0; then
    echo "pyBristol was removed." >&2
else
    echo "Something went wrong. Check manually if everything was removed." >&2
    exit 1
fi
